<?php

return [

    /**
     * Список областных центров.
     */

    "Vinnitsa"=>[
        "alias"=>"Vinnitsa",
        "name"=>"Винница",
        "translit"=>"Vinnitsa",
    ],
    "Odessa"=>[
        "alias"=>"Odessa",
        "name"=>"Одесса",
        "translit"=>"Odessa",
    ],
    "Poltava"=>[
        "alias"=>"Poltava",
        "name"=>"Полтава",
        "translit"=>"Poltava",
    ],
    "Rovno"=>[
        "alias"=>"Rovno",
        "name"=>"Ровно",
        "translit"=>"Rovno",
    ],
    "Sumy"=>[
        "alias"=>"Sumy",
        "name"=>"Сумы",
        "translit"=>"Sumy",
    ],
    "Ternopil"=>[
        "alias"=>"Ternopil",
        "name"=>"Тернополь",
        "translit"=>"Ternopol",
    ],
    "Kharkiv"=>[
        "alias"=>"Kharkiv",
        "name"=>"Харьков",
        "translit"=>"Kharkov",
    ],
    "Kherson"=>[
        "alias"=>"Kherson",
        "name"=>"Херсон",
        "translit"=>"Kherson",
    ],
    "Khmelnytskyi"=>[
        "alias"=>"Khmelnytskyi",
        "name"=>"Хмельницкий",
        "translit"=>"Khmelnitskiy",
    ],
    "Cherkassy"=>[
        "alias"=>"Cherkassy",
        "name"=>"Черкассы",
        "translit"=>"Cherkassy",
    ],
    "Chernigov"=>[
        "alias"=>"Chernigov",
        "name"=>"Чернигов",
        "translit"=>"Chernigov",
    ],
    "Mykolaiv"=>[
        "alias"=>"Mykolaiv",
        "name"=>"Николаев",
        "translit"=>"Nikolayev",
    ],
    "Lviv"=>[
        "alias"=>"Lviv",
        "name"=>"Львов",
        "translit"=>"Lvov",
    ],
    "Severodonetsk"=>[
        "alias"=>"Severodonetsk",
        "name"=>"Северодонецк",
        "translit"=>"Severodonetsk",
    ],
    "Lutsk"=>[
        "alias"=>"Lutsk",
        "name"=>"Луцк",
        "translit"=>"Lutsk",
    ],
    "Dnieper"=>[
        "alias"=>"Dnieper",
        "name"=>"Днепр",
        "translit"=>"Dnepr",
    ],
    "Donetsk"=>[
        "alias"=>"Donetsk",
        "name"=>"Донецк",
        "translit"=>"Donetsk",
    ],
    "Zhitomir"=>[
        "alias"=>"Zhitomir",
        "name"=>"Житомир",
        "translit"=>"Zhitomir",
    ],
    "Uzhhorod"=>[
        "alias"=>"Uzhhorod",
        "name"=>"Ужгород",
        "translit"=>"Uzhgorod",
    ],
    "Zaporozhye"=>[
        "alias"=>"Zaporozhye",
        "name"=>"Запорожье",
        "translit"=>"Zaporozhye",
    ],
    "Ivano-Frankivsk"=>[
        "alias"=>"Ivano-Frankivsk",
        "name"=>"Ивано-Франковск",
        "translit"=>"Ivano-Frankovsk",
    ],
    "Kiev"=>[
        "alias"=>"Kiev",
        "name"=>"Киев",
        "translit"=>"Kiyev",
    ],
    "Kropiwnicki"=>[
        "alias"=>"Kropiwnicki",
        "name"=>"Кропивницкий",
        "translit"=>"Kropivnitskiy",
    ],
    "Chernivtsi"=>[
        "alias"=>"Chernivtsi",
        "name"=>"Черновцы",
        "translit"=>"Chernovtsy",
    ],
];